config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#new'

  # Ransack用
  get '/index', to: 'posts#index'

  resources :posts
  resources :comments

  # お気に入り追加・削除
  get '/likes/:id', to: 'likes#touch'

  # フォロー・アンフォロー
  get '/follow/action', to: 'follows#touch'

  # RESTfulなルーティング
  resources :users

  # ログイン機能
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase } #email属性を小文字に変換してメールアドレスの一意性を保証する
  # 登録時のバリデーション
  validates :nickname, presence: true, length: { maximum: 20 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, #emailは空白にできない、文字数は255文字まで
            format: { with: VALID_EMAIL_REGEX }, #正規表現
            uniqueness: { case_sensitive: false } #同じemailは登録できない

  validates :image, presence: true, length: { maximum: 255 }

  has_secure_password #パスワードのハッシュ化

  #空白スペースなどは設定不可、最低文字数は6文字、プロフィール編集画面ではパスワード入力なしで更新可能
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す（８章の「8.2.4 レイアウトの変更をテストする」でも使う部分)
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    # remember_token = User.new_token

    #remember_digestカラムの値をハッシュ値で上書きしている引数は(remember_token)
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する（データベースから削除してる）
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # binding.pry
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user #app/helpers/sessions_helper.rb のメソッドを呼び出す

      #app/helpers/sessions_helper.rb のメソッドを呼び出す
      if params[:session][:remember_me] == '1'
        remember(user) #app/helpers/sessions_helper.rb のメソッドを呼び出す
      else
        forget(user) #app/helpers/sessions_helper.rb のメソッドを呼び出す
      end
      #上記のif文は下記のように三項演算子 で書くことも可能
      # params[:session][:remember_me] == '1' ? remember(user) : forget(user) #app/helpers/sessions_helper.rb のメソッドを呼び出す

      #app/helpers/sessions_helper.rb からメソッド呼び出し （記憶したURL (もしくはデフォルト値) にリダイレクト）
      redirect_back_or user
    else
      # エラーメッセージを作成する
      flash.now[:danger] = 'email/passwordの入力に誤りがあります'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ログインしてないユーザーはプロフィール編集ページにはアクセス不可
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  #間違って、他の人のプロフィール編集ページにアクセスできないようにする
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーを作成しました"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 更新に成功した場合を扱う。
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:nickname, :email, :password,
                                   :password_confirmation, :image)
    end

    # beforeアクション
    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location #app/helpers/sessions_helper.rb からメソッド呼び出し （アクセスしようとしたURLを覚えておく）
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認 =>アクセスしようとしているユーザーのIDと、今ログインしているユーザーのIDを比較している
    def correct_user
      @user = User.find(params[:id])

      #sessions_helper.rb からcurrent_user?(user)メソッドを呼び出す
      # current_user メソッドを呼び出して結果が「false」なら、root_urlにリダイレクトさせる
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "女装アイテム口コミアプリ"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember #app/models/user.rb のメソッドを呼び出す
    cookies.permanent.signed[:user_id] = user.id #cookiesに暗号化したuser.idを代入
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークンcookieに対応するユーザーを返す記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id]) #user_idという変数に、ログインしたユーザーのsession[:user_id]を代入

      #今ログインしているという意味のインスタンス変数@current_userに、usersテーブルからidで検索したユーザーの情報代入
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id]) #ここの処理がよく分からない
      user = User.find_by(id: user_id) #ここの処理がよく分からない
      if user && user.authenticated?(cookies[:remember_token]) #ここの処理がよく分からない
        log_in user #ここの処理がよく分からない
        @current_user = user #ここの処理がよく分からない
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する（cookiesを削除してる）
  def forget(user)
    user.forget #app/models/user.rb #ユーザーのログイン情報を破棄する メソッドを呼び出す
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user) # 永続的セッションを破棄する app/helpers/sessions_helper.rb 同じファイル内のメソッドを呼び出す
    session.delete(:user_id) #一時的なセッションを破棄する
    @current_user = nil
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 60 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.nickname, class: "gravatar")
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a href="/" class="navbar-brand">Top</a>
  <button class="navbar-toggler" type="button"
          data-toggle="collapse"
          data-target="#navmenu1"
          aria-controls="navmenu1"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navmenu1">
    <div class="navbar-nav">
      <% if logged_in? %>
        <%= link_to new_post_path, class: "nav-item nav-link" do %>
          <i class="fas fa-plus"></i>新規投稿
        <% end %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% @nickname = User.find_by(id: current_user.id) %>
            <%= @nickname.nickname %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <%= link_to "マイページを表示", user_path(current_user.id), class: 'dropdown-item' %>
            <%= link_to "ログアウト", logout_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </div>
        <%= link_to users_path, class: "nav-item nav-link" do %>
          <i class="fas fa-users"></i>ユーザー一覧
        <% end %>
      <% else %>
        <%= link_to "新規登録", new_user_path, class: 'nav-item nav-link' %>
        <%= link_to "ログイン", login_path, class: 'nav-item nav-link' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- bootstrap -->
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>

<%= render 'layouts/navbar' %>

<body>
<div class="container">

  <!--  フラッシュメッセージ-->
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>

  <!--  デバッグ用の表示-->
  <%= debug(params) if Rails.env.development? %>

</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :nickname %>
  <%= f.text_field :nickname, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :image, "プロフィール画像" %>
  <%= f.file_field :image, class: 'form-control' %><br>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <!--ここのテキストはedit.html.erbか、new.html.erbから受け取る-->
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<div class="col-xl-4 col-md-6 col-sm-12">
  <!-- Content -->
  <%= link_to user_path(user), class: "nav-item nav-link" do %>
    <%#= image_tag user.image_url(:thumb) %>
    <%= gravatar_for user, size: 50 %>
  <% end %>
  <p><%= user.nickname %></p>

<!--  今ログインしているユーザーがadmin（管理者）で、尚且「管理者以外のユーザー」でのみ「削除」リンクを表示させる-->
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "削除", user, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'プロフィールを更新') %>

<!--app/views/users/_form.html.erb のyield(:button_text)にテキストを渡す-->
<% provide(:button_text, 'プロフィールを更新') %>

<h1>プロフィールを更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <!--app/views/users/_form.html.erb のパーシャル呼び出す-->
    <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<div class="text-center mt-5 mb-5">
  <h2>ユーザー一覧</h2>
</div>

<%= will_paginate %>

<div class="row show_images text-center">

    <%= render @users %>

</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>

<!--app/views/users/_form.html.erb のyield(:button_text)にテキストを渡す-->
<% provide(:button_text, '新規登録') %>


<h1>新規登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <!--app/views/users/_form.html.erb のパーシャル呼び出す-->
    <%= render 'form' %>

  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.nickname}の詳細ページ") %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.nickname %>
</h1>

<div class="text-center">
  <button type="button" class="btn btn-secondary">
    <%= link_to "プロフィールを編集する", edit_user_path(current_user) %>
  </button>
</div>